name: Build, Publish

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish release?'
        required: false
        default: 'false'

jobs:
  build-and-publish:
    runs-on: windows-latest
    env:
      PROJECT_NAME: ExchangeTime

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_NAME }}.slnx

      - name: Build
        run: dotnet build ${{ env.PROJECT_NAME }}.slnx `
          --configuration Release --no-restore

      #- name: Test
      #  run: dotnet test ${{ env.PROJECT_NAME }}.slnx `
      #    --configuration Release --no-build

      - name: Publish executable
        run: dotnet publish ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj `
          -c Release --no-build -r win-x64 `
          --self-contained true -o ./publish

      - name: List fies
        run: ls ./publish

      - name: Zip published output
        id: publish
        shell: pwsh
        run: |
          [xml]$proj = Get-Content "./${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj"
          $version = $proj.Project.PropertyGroup.Version
          if (-not $version) { $version = "0.0.0" }
          Write-Output "version=$version" >> $env:GITHUB_OUTPUT
          $zipName = "${{ env.PROJECT_NAME }}-$version.zip"
          Write-Host "Creating release package: $zipName"
          Compress-Archive -Path ./publish/* -DestinationPath ./$zipName
          Write-Output "zipName=$zipName" >> $env:GITHUB_OUTPUT
          ls

      - name: Create GitHub Release
        if: ${{ github.event.inputs.publish == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.publish.outputs.version }}
          name: "${{ env.PROJECT_NAME }} v${{ steps.publish.outputs.version }}"
          files: ./${{ steps.publish.outputs.zipName }}
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
