name: Build, Publish

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish release?'
        required: false
        default: 'false'

jobs:
  build-and-publish:
    runs-on: windows-latest
    env:
      PROJECT_NAME: ExchangeTime

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_NAME }}.slnx

      - name: Build
        run: dotnet build ${{ env.PROJECT_NAME }}.slnx `
          --configuration Release --no-restore

      #- name: Test
      #  run: dotnet test ${{ env.PROJECT_NAME }}.slnx `
      #    --configuration Release --no-build

      - name: Publish win-x64 executable
        run: dotnet publish ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj `
          -c Release --no-build -r win-x64 `
          --self-contained true -o ./publish/win-x64

      - name: Publish win-arm64 executable
        run: dotnet publish ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj `
          -c Release -r win-arm64 `
          --self-contained true -o ./publish/win-arm64

      - name: List fies
        run: |
          ls ./publish/win-x6
          ls ./publish/win-arm64

      - name: Zip published output
        id: publish
        shell: pwsh
        run: |
          [xml]$proj = Get-Content "./${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj"
          $version = $proj.Project.PropertyGroup.Version
          if (-not $version) { $version = "0.0.0" }
          Write-Output "version=$version" >> $env:GITHUB_OUTPUT

          $zipX64 = "${{ env.PROJECT_NAME }}-$version-x64.zip"
          $zipArm64 = "${{ env.PROJECT_NAME }}-$version-arm64.zip"
          
          Write-Host "Creating release packages: $zipX64 and $zipArm64."
          Compress-Archive -Path ./publish/win-x64/* -DestinationPath ./$zipX64
          Compress-Archive -Path ./publish/win-arm64/* -DestinationPath ./$zipArm64
          
          Write-Output "zipX64=$zipX64" >> $env:GITHUB_OUTPUT
          Write-Output "zipArm64=$zipArm64" >> $env:GITHUB_OUTPUT
          ls

      - name: Create GitHub Release
        if: ${{ github.event.inputs.publish == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.publish.outputs.version }}
          name: "${{ env.PROJECT_NAME }} v${{ steps.publish.outputs.version }}"
          files: |
            ./${{ steps.publish.outputs.zipX64 }}
            ./${{ steps.publish.outputs.zipArm64 }}          
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
