name: Build, Publish

on:
  push:
    paths-ignore:
     - '.github/workflows/release.yml'
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish release?'
        required: false
        default: 'false'

jobs:
  build-and-publish:
    runs-on: windows-latest
    env:
      PROJECT_NAME: ExchangeTime

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_NAME }}.slnx

      - name: Build
        run: dotnet build ${{ env.PROJECT_NAME }}.slnx `
          --configuration Release --no-restore

      #- name: Test
      #  run: dotnet test ${{ env.PROJECT_NAME }}.slnx `
      #    --configuration Release --no-build

      - name: Publish executable
        run: dotnet publish ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj `
          -c Release -r win-x64 --self-contained true -o ./publish

      - name: List fies
        run: ls ./publish

      - name: Zip publish folder
        run: |
          cd publish
          powershell Compress-Archive -Path * -DestinationPath ../${{ env.PROJECT_NAME }}-${{ steps.get_version.outputs.version }}.zip

      - name: Extract project version
        id: get_version
        shell: pwsh
        run: |
           [xml]$proj = Get-Content "./YourProjectName/YourProjectName.csproj"
           $version = $proj.Project.PropertyGroup.Version
           if (-not $version) { $version = "0.0.0" }
           Write-Output "version=$version" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release
        if: github.event.inputs.publish == 'true'
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ needs.build.outputs.version }}
          generate_release_notes: false
          files: ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
